/* SPDX-License-Identifier: GPL-2.0 */
/*
* scx_gamer: Profiling Configuration Header
* Copyright (c) 2025 RitzDaCat
*
* This header is generated by build.rs at compile time.
* Controls compile-time profiling instrumentation for BPF hot paths.
*
* TIER 0: Compile-time configuration, zero runtime overhead when disabled.
*
* When profiling is DISABLED (default):
*   - This file contains only a comment (no #define)
*   - All profiling macros become no-ops: do {} while (0)
*   - Compiler optimizes away all profiling code entirely
*   - Zero runtime cost (Tier 0)
*
* When profiling is ENABLED (SCX_GAMER_ENABLE_PROFILING=1):
*   - This file contains: #define ENABLE_PROFILING
*   - Profiling macros become active (Tier 2: ~50-150ns overhead)
*   - Used for development/debugging only
*
* Performance Impact:
*   - Disabled: Tier 0 (0ns overhead, compile-time eliminated)
*   - Enabled: Tier 2 (~50-150ns per scheduling decision)
*
* Usage:
*   - Production builds: Profiling disabled (default)
*   - Debug builds: Profiling enabled via build.sh
*/
/* Profiling disabled */
