// Copyright (c) Andrea Righi <arighi@nvidia.com>
//
// This software may be used and distributed according to the terms of the
// GNU General Public License version 2.

fn main() {
    // Check if profiling should be enabled (via SCX_GAMER_ENABLE_PROFILING env var)
    // This is set by build.sh when building debug+profiling
    let enable_profiling = std::env::var("SCX_GAMER_ENABLE_PROFILING").is_ok();
    
    // Create profiling_config.h in the source directory (alongside main.bpf.c)
    // This ensures BPF compiler can find it since it compiles from source directory context
    // Use CARGO_MANIFEST_DIR to get the crate root directory
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR not set");
    let config_header_path = std::path::Path::new(&manifest_dir)
        .join("src")
        .join("bpf")
        .join("profiling_config.h");
    
    if enable_profiling {
        println!("cargo:warning=Profiling enabled (ENABLE_PROFILING flag set)");
        println!("cargo:warning=This adds ~50-150ns overhead per scheduling decision");
        // TIER 2: Profiling enabled - adds runtime overhead for development/debugging
        let profiling_enabled_content = "/* SPDX-License-Identifier: GPL-2.0 */\n\
/*\n\
 * scx_gamer: Profiling Configuration Header\n\
 * Copyright (c) 2025 RitzDaCat\n\
 *\n\
 * This header is generated by build.rs at compile time.\n\
 * Controls compile-time profiling instrumentation for BPF hot paths.\n\
 *\n\
 * TIER 2: Profiling enabled - adds ~50-150ns overhead per scheduling decision.\n\
 * Used for development/debugging only. Not recommended for production.\n\
 *\n\
 * Performance Impact:\n\
 *   - Enabled: Tier 2 (~50-150ns per scheduling decision)\n\
 *   - Disabled: Tier 0 (0ns overhead, compile-time eliminated)\n\
 */\n\
#define ENABLE_PROFILING\n";
        std::fs::write(&config_header_path, profiling_enabled_content)
            .expect("Failed to write profiling_config.h");
    } else {
        // TIER 0: Profiling disabled - zero runtime overhead (default for production)
        let profiling_disabled_content = "/* SPDX-License-Identifier: GPL-2.0 */\n\
/*\n\
 * scx_gamer: Profiling Configuration Header\n\
 * Copyright (c) 2025 RitzDaCat\n\
 *\n\
 * This header is generated by build.rs at compile time.\n\
 * Controls compile-time profiling instrumentation for BPF hot paths.\n\
 *\n\
 * TIER 0: Compile-time configuration, zero runtime overhead when disabled.\n\
 *\n\
 * When profiling is DISABLED (default):\n\
 *   - This file contains only a comment (no #define)\n\
 *   - All profiling macros become no-ops: do {} while (0)\n\
 *   - Compiler optimizes away all profiling code entirely\n\
 *   - Zero runtime cost (Tier 0)\n\
 *\n\
 * When profiling is ENABLED (SCX_GAMER_ENABLE_PROFILING=1):\n\
 *   - This file contains: #define ENABLE_PROFILING\n\
 *   - Profiling macros become active (Tier 2: ~50-150ns overhead)\n\
 *   - Used for development/debugging only\n\
 *\n\
 * Performance Impact:\n\
 *   - Disabled: Tier 0 (0ns overhead, compile-time eliminated)\n\
 *   - Enabled: Tier 2 (~50-150ns per scheduling decision)\n\
 *\n\
 * Usage:\n\
 *   - Production builds: Profiling disabled (default)\n\
 *   - Debug builds: Profiling enabled via build.sh\n\
 */\n\
/* Profiling disabled */\n";
        std::fs::write(&config_header_path, profiling_disabled_content)
            .expect("Failed to write profiling_config.h");
    }
    
    // Tell cargo to rerun if env var changes
    println!("cargo:rerun-if-env-changed=SCX_GAMER_ENABLE_PROFILING");
    println!("cargo:rerun-if-changed={}", config_header_path.display());
    
    scx_cargo::BpfBuilder::new()
        .unwrap()
        .enable_intf("src/bpf/intf.h", "bpf_intf.rs")
        .enable_skel("src/bpf/main.bpf.c", "bpf")
        .build()
        .unwrap();
}
